const translations={
ru:{newProject:'Новый проект',preview:'Предпросмотр',beta:'Beta · 0.4 Wire',title:'Создавай сайты визуально',subtitle:'Собирай элементы, соединяй действия в Blueprint и получай готовый сайт без сложного кода.',start:'Начать создавать →',demo:'Посмотреть демо',local:'✦ Работает прямо в браузере · без сервера',elements:'Элементы',basic:'Основные',text:'Текст',button:'Кнопка',counter:'Счётчик',container:'Контейнер',logic:'Логика',stylesTitle:'Предустановленные стили',stylesIntro:'Готовые визуальные основы. Нажми «Использовать» — стиль применится сразу.',minimalDesc:'Чистый и нейтральный',softDesc:'Мягкий и округлый',contrastDesc:'Яркий и выразительный',useStyle:'Использовать',visual:'Визуально',visualDesc:'Добавляй элементы на страницу и настраивай их.',blueprintDesc:'Соединяй события и действия блоками.',styles:'Стили',stylesDesc:'Используй готовые пресеты или свои CSS-стили.',export:'Экспорт',exportDesc:'Получай обычный HTML, CSS и JS.',settings:'Настройки Trista',settingsDesc:'Это настройки самого Trista, а не создаваемого проекта.',close:'Закрыть',appearance:'Тема',language:'Язык',styleChosen:'Стиль применён: ',light:'Светлая',dark:'Тёмная',system:'Системная',russian:'Русский',english:'English',themeHint:'Выбери внешний вид Trista',languageHint:'Выбери язык интерфейса',wireTitle:'Условия в Blueprint',wireIntro:'Теперь логика может принимать решение: если условие истинно — идём по True, иначе — по False.',runLogic:'Запустить',eventLabel:'Событие',conditionLabel:'Условие',conditionText:'Counter ≥ 3?',trueAction:'Показать успех',falseAction:'Counter +1',ready:'Готово',running:'Проверяем условие…',success:'TRUE → Условие выполнено',increment:'FALSE → Counter +1',newProjectToast:'Новый проект будет добавлен в редактор.',previewToast:'Предпросмотр готов.'},
en:{newProject:'New project',preview:'Preview',beta:'Beta · 0.4 Wire',title:'Build websites visually',subtitle:'Place elements, connect actions with Blueprint, and get a working website without complicated code.',start:'Start creating →',demo:'View demo',local:'✦ Works directly in your browser · no server',elements:'Elements',basic:'Basics',text:'Text',button:'Button',counter:'Counter',container:'Container',logic:'Logic',stylesTitle:'Built-in styles',stylesIntro:'Ready visual foundations. Press “Use” and the style applies instantly.',minimalDesc:'Clean and neutral',softDesc:'Soft and rounded',contrastDesc:'Bold and expressive',useStyle:'Use style',visual:'Visual',visualDesc:'Add elements to the page and customize them.',blueprintDesc:'Connect events and actions with blocks.',styles:'Styles',stylesDesc:'Use presets or your own CSS styles.',export:'Export',exportDesc:'Get plain HTML, CSS and JS.',settings:'Trista Settings',settingsDesc:'These settings belong to Trista itself, not to the website project.',close:'Close',appearance:'Theme',language:'Language',styleChosen:'Style applied: ',light:'Light',dark:'Dark',system:'System',russian:'Русский',english:'English',themeHint:'Choose how Trista looks',languageHint:'Choose interface language',wireTitle:'Conditions in Blueprint',wireIntro:'Logic can now make a decision: if the condition is true, follow True; otherwise follow False.',runLogic:'Run',eventLabel:'Event',conditionLabel:'Condition',conditionText:'Counter ≥ 3?',trueAction:'Show success',falseAction:'Counter +1',ready:'Ready',running:'Checking condition…',success:'TRUE → Condition passed',increment:'FALSE → Counter +1',newProjectToast:'A new project will be added to the editor.',previewToast:'Preview is ready.'}}

const detectLanguage=()=>{const list=[...(navigator.languages||[]),navigator.language||'en'];return list.some(x=>String(x).toLowerCase().startsWith('ru'))?'ru':'en'};
const detectTheme=()=>window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';
const savedLang=localStorage.getItem('trista-lang');
const savedTheme=localStorage.getItem('trista-theme');
const state={lang:savedLang||detectLanguage(),theme:['light','dark','system'].includes(savedTheme)?savedTheme:'system',style:localStorage.getItem('trista-style')||'Minimal'};
const t=()=>translations[state.lang];
const systemDark=()=>window.matchMedia('(prefers-color-scheme: dark)').matches;
const effectiveDark=()=>state.theme==='dark'||(state.theme==='system'&&systemDark());

function save(){localStorage.setItem('trista-lang',state.lang);localStorage.setItem('trista-theme',state.theme);localStorage.setItem('trista-style',state.style)}
function toast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.hidden=false;clearTimeout(window.tristaToast);window.tristaToast=setTimeout(()=>el.hidden=true,2200)}

function makeMenu(id,items){const el=document.createElement('div');el.id=id;el.className='quick-menu';el.hidden=true;el.innerHTML=items.map(x=>`<button data-value="${x.value}"><span>${x.icon}</span><b>${x.label}</b></button>`).join('');document.body.appendChild(el);return el}
const langMenu=makeMenu('langMenu',[{value:'ru',icon:'🇷🇺',label:'Русский'},{value:'en',icon:'🇬🇧',label:'English'}]);
const themeMenu=makeMenu('themeMenu',[{value:'light',icon:'☀',label:'Светлая'},{value:'dark',icon:'☾',label:'Тёмная'},{value:'system',icon:'◐',label:'Системная'}]);
function closeMenus(){[langMenu,themeMenu].forEach(m=>{m.classList.remove('open');m.hidden=true})}
function placeMenu(menu,anchor){const r=anchor.getBoundingClientRect();menu.style.top=`${r.bottom+9}px`;menu.style.right=`${Math.max(10,innerWidth-r.right)}px`;menu.hidden=false;requestAnimationFrame(()=>menu.classList.add('open'))}
function updateMenus(){langMenu.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===state.lang));themeMenu.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===state.theme))}

function render(){document.documentElement.lang=state.lang;document.body.classList.toggle('dark',effectiveDark());document.body.dataset.theme=state.theme;document.body.dataset.siteStyle=state.style.toLowerCase();document.querySelectorAll('[data-i18n]').forEach(el=>{const value=t()[el.dataset.i18n];if(value)el.textContent=value});const lang=document.getElementById('lang'),theme=document.getElementById('theme');if(lang)lang.textContent=state.lang==='ru'?'EN':'RU';if(theme)theme.textContent=effectiveDark()?'☀':'☾';document.querySelectorAll('[data-style]').forEach(b=>b.closest('.style-card')?.classList.toggle('selected',b.dataset.style===state.style));updateMenus();const themeState=document.getElementById('themeState'),langState=document.getElementById('langState');if(themeState)themeState.textContent=t()[state.theme];if(langState)langState.textContent=state.lang.toUpperCase()}

document.getElementById('theme')?.addEventListener('click',e=>{e.stopPropagation();if(themeMenu.hidden){closeMenus();placeMenu(themeMenu,e.currentTarget)}else closeMenus()});
document.getElementById('lang')?.addEventListener('click',e=>{e.stopPropagation();if(langMenu.hidden){closeMenus();placeMenu(langMenu,e.currentTarget)}else closeMenus()});
themeMenu.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.theme=b.dataset.value;save();closeMenus();render();toast(`${t().appearance}: ${t()[state.theme]}`)});
langMenu.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.lang=b.dataset.value;save();closeMenus();render();toast(state.lang==='ru'?'Язык изменён':'Language changed')});
document.addEventListener('click',e=>{if(!e.target.closest('.quick-menu')&&!e.target.closest('#theme')&&!e.target.closest('#lang'))closeMenus()});
window.addEventListener('resize',closeMenus);
window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')render()});

const panel=document.getElementById('panel');
function renderSettings(){if(!panel)return;panel.innerHTML=`<button class="close" id="closeSettings" aria-label="${t().close}">×</button><span class="section-kicker">APP</span><h2>${t().settings}</h2><p>${t().settingsDesc}</p><div class="setting-group"><div class="setting-title">${t().language}</div><small>${t().languageHint}</small><div class="setting-options"><button data-lang="ru">🇷🇺 ${t().russian}<span>✓</span></button><button data-lang="en">🇬🇧 ${t().english}<span>✓</span></button></div></div><div class="setting-group"><div class="setting-title">${t().appearance}</div><small>${t().themeHint}</small><div class="setting-options"><button data-theme="light">☀ ${t().light}<span>✓</span></button><button data-theme="dark">☾ ${t().dark}<span>✓</span></button><button data-theme="system">◐ ${t().system}<span>✓</span></button></div></div>`;panel.querySelector('#closeSettings').onclick=()=>panel.hidden=true;panel.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===state.lang);b.onclick=()=>{state.lang=b.dataset.lang;save();render();renderSettings();toast(state.lang==='ru'?'Язык изменён':'Language changed')}});panel.querySelectorAll('[data-theme]').forEach(b=>{b.classList.toggle('active',b.dataset.theme===state.theme);b.onclick=()=>{state.theme=b.dataset.theme;save();render();renderSettings();toast(`${t().appearance}: ${t()[state.theme]}`)}})}
document.getElementById('settings')?.addEventListener('click',()=>{panel.hidden=false;renderSettings()});

document.getElementById('newProject')?.addEventListener('click',()=>toast(t().newProjectToast));
document.getElementById('previewBtn')?.addEventListener('click',()=>document.getElementById('wireSection')?.scrollIntoView({behavior:'smooth',block:'start'}));
document.getElementById('demo')?.addEventListener('click',()=>document.getElementById('wireSection')?.scrollIntoView({behavior:'smooth',block:'center'}));
document.getElementById('start')?.addEventListener('click',()=>document.getElementById('wireSection')?.scrollIntoView({behavior:'smooth',block:'start'}));
document.querySelectorAll('[data-style]').forEach(btn=>btn.addEventListener('click',()=>{state.style=btn.dataset.style;save();render();toast(t().styleChosen+state.style)}));

let counter=0;
const runWire=document.getElementById('runWire');
const wireStatus=document.getElementById('wireStatus');
function runCondition(){if(!runWire||!wireStatus)return;wireStatus.textContent=`● ${t().running}`;runWire.disabled=true;document.getElementById('wireDemo')?.classList.add('running');setTimeout(()=>{const passed=counter>=3;if(!passed)counter++;wireStatus.textContent=`● ${passed?t().success:t().increment} · ${counter}`;document.getElementById('wireDemo')?.classList.remove('running');document.querySelector('.wire-branch.true')?.classList.toggle('active',passed);document.querySelector('.wire-branch.false')?.classList.toggle('active',!passed);runWire.disabled=false},500)}
runWire?.addEventListener('click',runCondition);

const polish=document.createElement('style');polish.textContent=`
body{min-height:100vh;overflow-x:hidden;-webkit-font-smoothing:antialiased}.topbar{box-shadow:0 1px 0 rgba(20,20,40,.025)}
button,a,.style-card,.features article,.builder-preview,.canvas-card,.mini-item,.nav button{transition:transform .2s ease,background .2s ease,border-color .2s ease,color .2s ease,box-shadow .2s ease,opacity .2s ease}
.brand-mark{animation:tristaFloat 4s ease-in-out infinite}.brand:hover .brand-mark{transform:rotate(-7deg) scale(1.06)}.nav button:hover{transform:translateY(-1px)}.nav button:active,.primary:active,.secondary:active,.style-info button:active{transform:scale(.96)}
.hero-copy{animation:tristaUp .7s cubic-bezier(.22,1,.36,1) both}.eyebrow{animation:tristaUp .7s .05s both}.builder-preview{animation:tristaPreview .8s .1s cubic-bezier(.22,1,.36,1) both}.builder-preview:hover{transform:rotate(0) translateY(-4px);box-shadow:0 34px 100px rgba(34,30,80,.18)}
.status-dot,.window-head i{animation:tristaPulse 2s ease-in-out infinite}.primary:hover{transform:translateY(-2px);box-shadow:0 16px 38px rgba(102,92,255,.34)}.secondary:hover{transform:translateY(-2px);box-shadow:0 10px 25px rgba(30,30,60,.08)}
.canvas-card{animation:tristaFloatCard 5s ease-in-out infinite}.canvas-card:hover{transform:translateY(-3px)}.selection-tag{animation:tristaTag 2.4s ease-in-out infinite}.mini-item:hover{transform:translateX(2px);background:var(--surface);color:var(--text)}
.style-card{position:relative;animation:tristaUp .6s both}.style-card:nth-child(1){animation-delay:.08s}.style-card:nth-child(2){animation-delay:.16s}.style-card:nth-child(3){animation-delay:.24s}.style-card:hover{transform:translateY(-5px);box-shadow:0 22px 50px rgba(30,30,60,.12)}.style-card.selected{box-shadow:inset 0 0 0 2px var(--accent),0 18px 45px rgba(30,30,60,.1)}.style-card.selected .style-info button{background:var(--accent);border-color:var(--accent);color:#fff}.style-card.selected .style-info button:after{content:' ✓'}.features article{animation:tristaUp .6s both}.features article:nth-child(1){animation-delay:.08s}.features article:nth-child(2){animation-delay:.14s}.features article:nth-child(3){animation-delay:.2s}.features article:nth-child(4){animation-delay:.26s}.features article:hover{transform:translateY(-4px);box-shadow:0 16px 38px rgba(30,30,60,.09)}
.settings{backdrop-filter:blur(22px);animation:tristaPanel .25s cubic-bezier(.22,1,.36,1)}.settings .close:hover{transform:rotate(90deg)}.setting-group{border-top:1px solid var(--border);padding:16px 0}.setting-title{font-weight:800;margin-bottom:4px}.setting-group small{display:block;color:var(--muted);margin-bottom:10px}.setting-options{display:grid;gap:7px}.setting-options button{display:flex;align-items:center;gap:9px;width:100%;padding:11px 12px;border:1px solid var(--border);border-radius:11px;background:var(--surface2);color:var(--text);text-align:left}.setting-options button span{margin-left:auto;opacity:0;color:var(--accent);font-weight:900}.setting-options button.active{border-color:var(--accent);background:rgba(103,88,245,.1);color:var(--accent)}.setting-options button.active span{opacity:1}
.quick-menu{position:fixed;min-width:180px;padding:7px;border:1px solid var(--border);border-radius:14px;background:rgba(255,255,255,.94);backdrop-filter:blur(22px);box-shadow:0 18px 55px rgba(20,20,50,.16);z-index:100;opacity:0;transform:translateY(-5px) scale(.98);transition:.16s}.quick-menu.open{opacity:1;transform:none}.quick-menu button{display:flex;align-items:center;gap:10px;width:100%;padding:10px 11px;border:0;border-radius:9px;background:transparent;color:var(--text);text-align:left}.quick-menu button:hover,.quick-menu button.active{background:var(--surface2)}.quick-menu button.active{color:var(--accent)}.quick-menu button span{width:20px;text-align:center}
.wire-demo{border:1px solid var(--border);border-radius:20px;background:var(--surface);box-shadow:var(--shadow);overflow:hidden}.wire-toolbar{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid var(--border);background:var(--surface2)}.wire-status{font-size:12px;color:var(--muted);font-weight:700}.wire-demo.running .wire-status{color:var(--accent);animation:tristaPulse .7s infinite}.wire-toolbar .small-action{padding:9px 13px}.wire-toolbar button:disabled{opacity:.55;cursor:wait}.wire-flow{display:flex;align-items:center;gap:12px;padding:28px;min-height:190px;flex-wrap:wrap}.wire-node{min-width:150px;padding:15px;border:1px solid var(--border);border-radius:14px;background:var(--surface2);display:flex;flex-direction:column;gap:7px}.wire-node small{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:1px}.wire-node b{font-size:14px}.wire-node.trigger{border-color:#8d87ff}.wire-node.condition{border-color:#e5a768}.wire-arrow{font-size:24px;color:var(--muted)}.wire-branches{display:grid;gap:9px;min-width:230px;flex:1}.wire-branch{display:flex;align-items:center;gap:10px;padding:11px 13px;border:1px solid var(--border);border-radius:12px;background:var(--surface2);font-size:12px;transition:.25s}.wire-branch span{font-size:9px;font-weight:900;letter-spacing:1px}.wire-branch.true span{color:#4ca876}.wire-branch.false span{color:#d18a42}.wire-branch i{font-style:normal;color:var(--muted)}.wire-branch.active{transform:translateX(5px);box-shadow:0 8px 22px rgba(30,30,60,.1);border-color:var(--accent)}
body.dark .quick-menu{background:rgba(20,22,28,.95)}
@keyframes tristaUp{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}@keyframes tristaPreview{from{opacity:0;transform:translateY(25px) rotate(2deg) scale(.97)}to{opacity:1;transform:rotate(.35deg) scale(1)}}@keyframes tristaPanel{from{opacity:0;transform:translateY(-7px) scale(.98)}to{opacity:1;transform:none}}@keyframes tristaFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-2px)}}@keyframes tristaPulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.55;transform:scale(.84)}}@keyframes tristaTag{0%,100%{box-shadow:0 0 0 rgba(102,92,255,0)}50%{box-shadow:0 0 0 5px rgba(102,92,255,.12)}}@keyframes tristaFloatCard{0%,100%{transform:translateY(0)}50%{transform:translateY(-2px)}}
@media(max-width:700px){.wire-flow{padding:18px;display:grid;grid-template-columns:1fr}.wire-arrow{transform:rotate(90deg);justify-self:center}.wire-branches{min-width:0}.wire-node{min-width:0}.wire-toolbar{padding:12px}.wire-branch{font-size:11px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.01ms!important}}
`;
document.head.appendChild(polish);
render();