const state={lang:localStorage.getItem('trista-lang')||'ru',dark:localStorage.getItem('trista-theme')==='dark'};
const translations={
 ru:{newProject:'Новый проект',preview:'Предпросмотр',title:'Создавай сайты визуально',subtitle:'Собирай элементы, соединяй действия в Blueprint и получай готовый сайт без сложного кода.',start:'Начать создавать',demo:'Посмотреть демо',elements:'Элементы',text:'Текст',button:'Кнопка',counter:'Счётчик',container:'Контейнер',visual:'Визуально',visualDesc:'Добавляй элементы на страницу и настраивай их.',blueprintDesc:'Соединяй события и действия блоками.',styles:'Стили',stylesDesc:'Используй предустановленные стили и темы.',export:'Экспорт',exportDesc:'Получай обычный HTML, CSS и JS.',settings:'Настройки Trista',settingsDesc:'Это настройки самого Trista, а не создаваемого проекта.',close:'Закрыть'},
 en:{newProject:'New project',preview:'Preview',title:'Build websites visually',subtitle:'Place elements, connect actions with Blueprint, and get a working website without complicated code.',start:'Start creating',demo:'View demo',elements:'Elements',text:'Text',button:'Button',counter:'Counter',container:'Container',visual:'Visual',visualDesc:'Add elements to the page and customize them.',blueprintDesc:'Connect events and actions with blocks.',styles:'Styles',stylesDesc:'Use built-in styles and themes.',export:'Export',exportDesc:'Get plain HTML, CSS and JS.',settings:'Trista Settings',settingsDesc:'These settings belong to Trista itself, not to the website project.',close:'Close'}
};
function render(){document.documentElement.lang=state.lang;document.body.classList.toggle('dark',state.dark);document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=translations[state.lang][el.dataset.i18n]||el.textContent);document.getElementById('langBtn').textContent=state.lang==='ru'?'EN':'RU';document.getElementById('themeBtn').textContent=state.dark?'☀':'☾';}
document.getElementById('themeBtn').onclick=()=>{state.dark=!state.dark;localStorage.setItem('trista-theme',state.dark?'dark':'light');render()};
document.getElementById('langBtn').onclick=()=>{state.lang=state.lang==='ru'?'en':'ru';localStorage.setItem('trista-lang',state.lang);render()};
const panel=document.getElementById('settingsPanel');document.getElementById('settingsBtn').onclick=()=>panel.hidden=false;document.getElementById('closeSettings').onclick=()=>panel.hidden=true;
document.getElementById('demoBtn').onclick=()=>document.querySelector('.builder-preview').scrollIntoView({behavior:'smooth',block:'center'});
document.getElementById('startBtn').onclick=()=>alert(state.lang==='ru'?'Редактор Trista скоро будет здесь — это Seed-версия.':'The Trista editor is coming soon — this is the Seed version.');
render();